### ISSUE TITLE
Overlay not working on my Mister

### ISSUE THREAD

**Issue by lroby74** [MiSTer-devel/Vectrex_MiSTer#6]
Hello,
i've unzipped overlays.zip file into Vectrex's games folder and tried a pair of games... but while game works perfectly, graphic of overylay doesn't work and show a lot of oblique stripes in upper section of screen..
Same game and overlay on Mister of my friend works perfectly..
Please help me to understand where is problem :(

**Comment by lroby74** [comment]
I've tried on a second Mister with same issue, both have 128 mb SDRAM

**Comment by sorgelig** [comment]
This is development site, not forum. Overlays work fine - i've just checked.
If you have problem with core use, please use forum: www.misterfpga.org
